tap_shopify/streams/base.py
=> fixing rate issue

tap_shopify/__init__.py
=> removing comment

tap_shopify/__init__.py
=> fixing validation issue

tap_shopify/schemas/discount_codes.json, tap_shopify/schemas/price_rules.json, tap_shopify/streams/__init__.py, tap_shopify/streams/base.py, tap_shopify/streams/child_stream.py, tap_shopify/streams/discounts_codes.py, tap_shopify/streams/order_refunds.py, tap_shopify/streams/price_rules.py
=> Adding discount codes and price rules

tap_shopify/schemas/price_rules.json
=> add columns to price rules

tap_shopify/streams/base.py
=> changing updated to created at and adding one second for duplicates

tap_shopify/__init__.py
=> adding stop import flag

tap_shopify/streams/base.py
=> handling connection errors and retrying

tap_shopify/schemas/order_refunds.json, tap_shopify/schemas/transactions.json, tap_shopify/streams/base.py, tap_shopify/streams/graph_ql_stream.py, tap_shopify/streams/order_refunds.py, tap_shopify/streams/transactions.py
=> using graph ql for transactions and order refunds

tap_shopify/__init__.py, tap_shopify/streams/base.py
=> adding limit to wait time

tap_shopify/streams/base.py
=> handling error for execution

tap_shopify/streams/base.py
=> increase retries

tap_shopify/streams/base.py
=> fixing printing issue

tap_shopify/streams/base.py
=> refactoring

tap_shopify/streams/base.py
=> handling connection reset error

tap_shopify/streams/base.py
=> adding incomplete read handle

tap_shopify/remember_errors_backoff.py
=> try sleeping longer the more 429 there were within the last minute

tap_shopify/__init__.py, tap_shopify/schemas/inventory_items.json, tap_shopify/schemas/inventory_levels.json, tap_shopify/schemas/locations.json, tap_shopify/streams/__init__.py, tap_shopify/streams/base.py, tap_shopify/streams/child_stream.py, tap_shopify/streams/inventory_items.py, tap_shopify/streams/inventroy_levels.py, tap_shopify/streams/locations.py
=> adding inventory tables

tap_shopify/schemas/locations.json
=> adding id column to location

tap_shopify/schemas/locations.json, tap_shopify/streams/locations.py
=> adding key properties to locations

tap_shopify/streams/graph_ql_stream.py, tap_shopify/streams/order_refunds.py
=> increasing limit for refunds

tap_shopify/schemas/orders.json
=> adding new columns to orders

tap_shopify/streams/order_refunds.py
=> increase refund limit

tap_shopify/streams/base.py, tap_shopify/streams/graph_ql_stream.py, tap_shopify/streams/locations.py
=> Refunds prop

setup.py, tap_shopify/__init__.py, tap_shopify/schemas/payouts.json, tap_shopify/streams/__init__.py, tap_shopify/streams/base.py, tap_shopify/streams/orders.py, tap_shopify/streams/payouts.py
=> adding inventory items table

tap_shopify/streams/base.py, tap_shopify/streams/payouts.py
=> done with adding skip day

tap_shopify/schemas/payouts.json
=> adding columns to payouts

tap_shopify/schemas/balance_transactions.json, tap_shopify/streams/__init__.py, tap_shopify/streams/balance_transactions.py
=> balance payout transactions

tap_shopify/streams/__init__.py, tap_shopify/streams/customer_journey.py
=> fixing customer journey issue

setup.py
=> adding graph ql builder

tap_shopify/streams/customer_journey.py
=> removing replication key

tap_shopify/streams/customer_journey.py
=> Refactor graphql

tap_shopify/streams/base.py, tap_shopify/streams/graph_ql_stream.py
https://app.clickup.com/t/2575789/TECH-3142
=> Tech 3142 - yearly timeframe on historical data will be extended until first record occurrence

tap_shopify/streams/base.py, tap_shopify/streams/graph_ql_stream.py
https://app.clickup.com/t/2575789/TECH-6239
=> add max allowed import time 24 hours

tap_shopify/streams/base.py
=> clean code

tap_shopify/schemas/transactions.json
https://app.clickup.com/t/2kczny4
=> add transaction fees

tap_shopify/streams/transactions.py
https://app.clickup.com/t/2575789/TECH-10064
=> fix NoneType object has not attribute replace
